-keep class pro.onephone.callfilter.** { *; }
-keep class com.android.billingclient.** { *; }
-keep class android.telephony.TelephonyManager { *; }
-keep class com.android.internal.telephony.ITelephony { *; }
-dontwarn org.json.**
-keep class org.json.** { *; }
-keep public class * extends android.app.Activity
-keep public class * extends android.telecom.CallScreeningService
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
